# Generated by Django 6.0 on 2026-02-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='imagem',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
